// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.WorldTime
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("search")]
        public string Search { get; set; }

        [JsonProperty("foundCities")]
        public FoundCity[] FoundCities { get; set; }
    }

    public partial class FoundCity
    {
        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("city_ascii")]
        public string CityAscii { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("iso2")]
        public string Iso2 { get; set; }

        [JsonProperty("iso3")]
        public string Iso3 { get; set; }

        [JsonProperty("province")]
        public string Province { get; set; }

        [JsonProperty("timezone")]
        public string Timezone { get; set; }

        [JsonProperty("time")]
        public string Time { get; set; }

        [JsonProperty("time24")]
        public DateTimeOffset Time24 { get; set; }

        [JsonProperty("time12")]
        public string Time12 { get; set; }

        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }

        [JsonProperty("day")]
        public string Day { get; set; }

        [JsonProperty("month")]
        public string Month { get; set; }

        [JsonProperty("year")]
        public long Year { get; set; }

        [JsonProperty("unix")]
        public long Unix { get; set; }

        [JsonProperty("dst")]
        public bool Dst { get; set; }

        [JsonProperty("dst_start")]
        public DateTimeOffset DstStart { get; set; }

        [JsonProperty("dst_end")]
        public DateTimeOffset DstEnd { get; set; }

        [JsonProperty("dst_name")]
        public string DstName { get; set; }

        [JsonProperty("state_ansi", NullValueHandling = NullValueHandling.Ignore)]
        public string StateAnsi { get; set; }
    }
}
